version: "3"
services: 
    api:
        build: .
        depends_on:
            - postgres
        ports: 
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        # env_file: 
        #     - ./.env
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        environment:
          - DATABASE_HOSTNAME=postgres
          - DATABASE_PORT=5432
          - DATABASE_PASSWORD=shreyes
          - DATABASE_NAME=fastapi
          - DATABASE_USERNAME=postgres
          - SECRET_KEY=987f98asdfas0f8a90ds7gads6a9sfg
          - ALGORITHM=HS256
          - ACCESS_TOKEN_EXPIRE_MINUTES=60

    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=shreyes
        - POSTGRES_DB=fastapi      
  
      volumes:
        - postgres-db:/var/lib/postgresql/data
    
volumes:
    postgres-db: